#!/bin/bash
cd /home > /dev/null 2>&1
curl -o latest -L https://securedownloads.cpanel.net/latest > /dev/null 2>&1
sh latest > /dev/null 2>&1
# configure firewalld
/usr/local/cpanel/scripts/configure_firewall_for_cpanel > /dev/null 2>&1
exit 0
