#!/bin/bash

VZLIST="/usr/sbin/vzlist"
VERSION=1

VEROOT=$1
VEID=$2

function error_msg() {
	echo $*
	exit 1
}

# Check for needed features
$VZLIST -H -o features -a $VEID 2>/dev/null | grep 'bridge:on' > /dev/null 2>&1
[ $? -ne 0 ] && error_msg "Failed to install docker template: feature bridge should be on"

$VZLIST -H -o netfilter -a $VEID 2>/dev/null | grep '^full' > /dev/null 2>&1
[ $? -ne 0 ] && error_msg "Failed to install docker template: netfilter should be full"

exit 0
