#!/bin/sh
# Perform actions scheduled for EZ template post-install
if [ -f /tmp/pp-bootstrapper-ez-templates-post-install.sh ]; then
        if ! /bin/sh /tmp/pp-bootstrapper-ez-templates-post-install.sh http://autoinstall.plesk.com/ ; then
            touch /var/lock/parallels-panel-upgrade-failure.flag
        fi
fi
# Apply patches if needed
if [ -f /var/lock/parallels-panel-apply-microupdates.flag ]; then
        ai_bin="/usr/local/psa/admin/sbin/autoinstaller"
        if [ -x "$ai_bin" ]; then
                $ai_bin --select-product-id plesk --select-release-current --upgrade-installed-components --reinstall-patch --separate-logs 2>/dev/null 1>/dev/null
        fi
fi

touch /usr/local/psa/var/installed-by-major

# clean-up
rm -f   /tmp/pp-bootstrapper-mode.flag  /tmp/pp-bootstrapper-ez-templates-prep-install.flag     /tmp/pp-bootstrapper-ez-templates-post-install.sh       /var/lock/parallels-panel-apply-microupdates.flag       /var/lock/parallels-panel-maintenance-mode.flag
true
