#!/bin/sh
# Set maintenance mode for panel
rm -f /var/lock/parallels-panel-upgrade-failure.flag
touch /var/lock/parallels-panel-maintenance-mode.flag

# Signal to install patches after installation
touch /var/lock/parallels-panel-apply-microupdates.flag

# Set bootstrapper mode flag to skip bootstrapper actions during package installation.
[ -f /tmp/pp-bootstrapper-mode.flag ] ||        touch /tmp/pp-bootstrapper-mode.flag
# Set special EZ template flag to schedule  EZ template post-install actions
# during package installing/updating.
# 1. Package scriptlets schedule re-applying of micro-update
#    when any product packages installed/updated.
# 2. Package scriptlets schedule performing bootstrapper actions
#    when any of packages bound to bootstrapper installed/updated.
[ -f /tmp/pp-bootstrapper-ez-templates-prep-install.flag ] ||   touch /tmp/pp-bootstrapper-ez-templates-prep-install.flag
true
